<?php
/**
 * Created by PhpStorm.
 * User: tinaa
 * Date: 14/03/2019
 * Time: 08:48
 */

namespace App\Actions\Expire;


use App\Expire;

class CreateFromExistingSubscription extends Create
{
    public function execute(Array $attributes): Expire
    {


        $expire = parent::execute($attributes); // TODO: Change the autogenerated stub

        $expire->order()->save(new Order(['amount' => 25, 'user_id' => $attributes['user_id']]));

        return $expire;
    }

}
